python manage.py loaddata "$(pwd)/Survey/survey/fixtures/survey.json"
python manage.py loaddata "$(pwd)/Survey/survey/fixtures/radio_question.json"
python manage.py loaddata "$(pwd)/Survey/survey/fixtures/radio_answer.json"
python manage.py loaddata "$(pwd)/Survey/survey/fixtures/integer_question.json"
python manage.py loaddata "$(pwd)/Survey/survey/fixtures/country_question.json"
