# Generated by Django 4.2 on 2023-04-12 14:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="radioanswer",
            old_name="answer",
            new_name="text",
        ),
    ]
