# Generated by Django 4.2 on 2023-04-12 14:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_rename_answer_radioanswer_text"),
    ]

    operations = [
        migrations.RenameField(
            model_name="radioquestion",
            old_name="question",
            new_name="text",
        ),
    ]
